id: P4EE66991
initial_creation_type: input
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA3JT13374
  instance_id: http://purl.bdrc.io/resource/IE3JT13374
  collection_id: http://purl.bdrc.io/resource/PR0ET010
  language_id: None
  title:
    bo:
    - སྡོམ་གསུམ་ཉེར་མཁོའི་བུམ་བཟང་།
  alt_title:
    bo:
    - སྡོམ་གསུམ་རྣམ་པར་བསྟན་པ་ཉེར་མཁོའི་བུམ་བཟང་།
  author: http://purl.bdrc.io/resource/P1361
  publisher: Various
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    d50cb3b7dc6c4826830233e27d6c5757:
      title: ༄༅།་།བདག་ཅག་གི་སྟོན་པ་ཐུབ་པའི་དབང་པོ་མཆོག་ཞིང་འདིར་བྱོན་ཏེ་ཆོས་ཀྱི་འཁོར་ལོ་བསྐོར་ནས།དམ་པའི་ཆོས་རིམ་གྱིས་འཕེལ་ཞིང་དར་བའི་གནས་སྐབ
      volume_number: 1
      base_file: UT3JT13374_001_0001.txt
      reference: http://purl.bdrc.io/resource/VLE76BFE2B5916129F
      image_group: null
      quality: null
  reproductionOf: []
created_at: '2021-12-31T08:20:50.983915'
last_modified_at: '2021-12-31T08:20:50.983921'
statistics:
  total_words: 82493
  total_non_words: 10265
quality:
  non_words_ratio: 0.12
